
- name: Install WordPress
  hosts: servers
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - libapache2-mod-php
          - php-mysql
          - php-mysqli
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - php-soap
          - php-intl
          - php-zip
          - python3-mysqldb

    - name: Start Apache service
      service:
        name: apache2
        state: started

    - name: Download and extract WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/wordpress.tar.gz"

    - name: Extract WordPress
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www/html/"
        remote_src: yes

    - name: Set ownership and permissions
      file:
        path: "/var/www/html/wordpress"
        owner: www-data
        group: www-data
        mode: 0755

    - name: Create MySQL database
      become: true
      shell: "mysql -e 'CREATE DATABASE WP_DEMO_DB;'"

    - name: Create MySQL database
      become: yes
      shell: "mysql -e 'CREATE DATABASE IF NOT EXISTS WP_DEMO_DB;'"

    - name: Create MySQL user and grant privileges
      become: yes
      shell: "mysql -e \"CREATE USER '{{ your_mysql_user }}'@'localhost' IDENTIFIED BY '{{ your_mysql_password }}'; GRANT ALL PRIVILEGES ON TEST2.* TO '{{ your_mysql_user }}'@'localhost'; FLUSH PRIVILEGES;\""

  vars:
    your_mysql_user: "your_mysql_user"
    your_mysql_password: "Abcd1234!@#$"

